//
// Created by fred.nicolson on 12/07/18.
//

#ifndef FRNETLIB_VERSION_H
#define FRNETLIB_VERSION_H

//Format: Major | Minor | Patch

#define FRNETLIB_VERSION_MAJOR  1
#define FRNETLIB_VERSION_MINOR  1
#define FRNETLIB_VERSION_PATCH  1

#define FRNETLIB_VERSION_NUMBER (FRNETLIB_VERSION_MAJOR * 100*100 + FRNETLIB_VERSION_MINOR * 100 + FRNETLIB_VERSION_PATCH)
#define FRNETLIB_VERSION_STRING "1.1.1"
#define FRNETLIB_VERSION_STRING_FULL "frnetlib 1.1.1"

#endif //FRNETLIB_VERSION_H
